### ISSUE TITLE
[Need support]: Error in docker-compose version support 

### ISSUE THREAD

**Issue by Advinsteve** [healenium/healenium#10]
### Describe the problem

I cannot decompose healinium-appium using docker 

![Screenshot from 2023-02-13 17-03-14](https://user-images.githubusercontent.com/122354351/218504100-f1e5a079-7230-48b6-bbd7-df0524e764b4.png)

### Healenium Web version

None

### Healenium Backend version

None

### Logs appeared during using Healenium

```shell
docker-compose -f docker-compose-appium.yaml up -d
ERROR: Version in "./docker-compose-appium.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Comment by Advinsteve** [comment]
docker-compose version 1.25.0, build unknown

**Comment by Alex-Reif** [comment]
Hi @Advinsteve , Update your docker please
