### ISSUE TITLE
[Need support]: Healing in ROBOT test automation framework is not working

### ISSUE THREAD

**Issue by ap0087105** [healenium/healenium#19]
### Describe the problem

We have implemented test scripts using ROBOT Framework. Executed those test cases successfully 4-5 time using Healenium without docker setup. Now http://localhost:7878/healenium/selectors/  screen shows enable_healing column value as false for all web elements. 
So if there is any locator change on web page, healing is not happening for that web element and test case is getting failed.  So is it new future,  Do we have to manually change enable_healing as true for each web element on selector url ? 

We are using :
HLM_PROXY_VERSION="1.3.3"
Healenium Backend version = 3.3.4
Selenium version = 4.8
browser = Edge 

### Healenium Web version

3.3.4

### Healenium Backend version

3.3.4

### Selenium version

4.8.3

### Platform

Python 

### Logs appeared during using Healenium

```shell
NA
```

**Comment by Alex-Reif** [comment]
Hi @ap0087105 , By default, Healenium performs healing on all findElement methods executed during the testing session. However, healing is not performed when using findElements methods. If you want to enable healing for findElements, you can do so by toggling the relevant selector on the Healenium selectors page.

More details here: https://healenium.io/docs/disable_healing
