### ISSUE TITLE
[Need support]: Changing the healenium user, schema and db name?

### ISSUE THREAD

**Issue by Kay63-sudo** [healenium/healenium#24]
### Describe the problem

I changed the healenium user name and schema in the docker compose file and the init.sql file. But I'm getting exceptions in docker. Is it possible to change these fields?

### Healenium Web version

3.4.3

### Healenium Backend version

3.3.4

### Selenium version

4.5.0

### Platform

Java

### Logs appeared during using Healenium

-08-11 09:52:14 healeniumAuto          | 2023-08-11 08:52:14.801 ERROR 1 - [       main] o.s.boot.SpringApplication       : Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "healenium_userCustom"\n  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)\n    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)\n      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)\n        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)\n      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\n  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)\n       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\n         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)\n       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\n         at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)\n        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)\n         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)\n         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)\n        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)\n      at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)\n       at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)\n         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)\n         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)\n         at com.epam.healenium.Application.main(Application.java:9)\n    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n       at java.lang.reflect.Method.invoke(Method.java:498)\n   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)\n      at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)\n         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)\n   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)\n Caused by: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "healenium_userCustom"\n     at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:271)\n   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n   ... 26 common frames omitted\n Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "healenium_userCustom"\n       at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)\n       at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)\n     at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)\n     at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)\n     at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)\n     at org.postgresql.Driver.makeConnection(Driver.java:458)\n       at org.postgresql.Driver.connect(Driver.java:260)\n     at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)\n    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)\n    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)\n    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)\n      at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)\n        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)\n      at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)\n         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:266)\n   ... 28 common frames omitted\n

**Comment by Alex-Reif** [comment]
Hi @Kay63-sudo , Yes, you can use your custom database name/schema/user for Healenium.

1.	Specify your data in the deb/sql/init.sql file

CREATE SCHEMA <custom_db_shema> AUTHORIZATION <custom_user_name>;
GRANT USAGE ON SCHEMA <custom_db_shema>TO <custom_user_name>;

2.	Change env. variables of postgresql service

environment:
         - POSTGRES_DB=<custom_db_name>
         - POSTGRES_USER=<custom_user_name>
         - POSTGRES_PASSWORD=<custom_user_password>

3.	Change env. variables of hlm-backend service

environment:
           - SPRING_POSTGRES_DB=<custom_db_name>
           - SPRING_POSTGRES_SCHEMA=<custom_db_shema>
           - SPRING_POSTGRES_USER=<custom_user_name>
           - SPRING_POSTGRES_PASSWORD=<custom_user_password>

**Comment by Alex-Reif** [comment]
" ERROR: no schema has been selected to create" Kindly check your settings
