### ISSUE TITLE
[Need support]:  is it possible to configure MYSQL instead of postgres

### ISSUE THREAD

**Issue by Divine1** [healenium/healenium#25]
### Describe the problem

we are already using mysql 8.0.31 server in our project. kindly let me know if   it is possible to configure MYSQL instead of postgres?

### Healenium Web version

3.8

### Healenium Backend version

3.4.0

### Selenium version

4

### Platform

Java

### Logs appeared during using Healenium

```shell
NA
```

**Comment by Alex-Reif** [comment]
Hello @Divine1 , Configuring Healenium with a different database is not supported. However, Healenium may offer these enhancements as part of paid support services.
