### ISSUE TITLE
[BUG]: When mapping an object that does not have an attribute, the error a.hasAttribute is not a function is displayed

### ISSUE THREAD

**Issue by TestAutomationRecruitmentQAEngineer** [healenium/healenium#26]
### Describe the bug

There is an element:

input lwc-enmikoh2qu="" class="slds-input" aria-errormessage="help-message-115" id="input-115" name="tel" part="input" pattern="^([0-9]{2}[\.]?[0-9]{3}[\.]?[0-9]{3}[\/]?[0-9]{4}[-]?[0-9]{2})|([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{2})$" type="text"

We map using label above input to indentify input text. This it is **xpath** **//label[text()='Número do Documento']/../div/input**

When trying to perform actions within complex elements (which do not have standard locators), healenium is unable to save the element's properties, presenting the error: a.hasAttribute is not a function.

Error log:
[main] WARN healenium - [Save Elements] Error during save elements: [8AE8547E638761A3972C3330F759A22D_element_3]. Message: javascript error: a.hasAttribute is not a function
  (Session info: chrome=117.0.5938.92)
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [e800f12ad900e73fd825b1075e3a326f, executeScript {script=var items = [];var result = {items: null, url: null};var a = arguments[0];while (a != document) {  var child = a;  var i=0; while(child=child.previousElementSibling) i++;  var node = {tag:null,id:null,index:null,classes:[],other:{},innerText:""};  if (a.tagName !== undefined) {    node.tag = a.tagName.toLowerCase();  }  node.id = a.id;  node.index = i;  node.innerText = a.innerText;  if (a.hasAttribute("class")) {	  node.classes = a.attributes.class.value.split(' ');  }  for (index = 0; index < a.attributes.length; ++index) {      var attrName = a.attributes[index].name;      if (["id","class"].indexOf(attrName) == -1){		    node.other[attrName] = a.attributes[index].value;      }  };  items.unshift(node);  a = a.parentNode;}result.items = items;result.url = window.location.href;return JSON.stringify(result);, args=[{ELEMENT=8AE8547E638761A3972C3330F759A22D_element_3, element-6066-11e4-a52e-4f735466cecf=8AE8547E638761A3972C3330F759A22D_element_3}]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 117.0.5938.92, chrome: {chromedriverVersion: 116.0.5845.96 (1a3918166880..., userDataDir: C:\Users\A0096122\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50580}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:50580/devtoo..., se:cdpVersion: 117.0.5938.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: e800f12ad900e73fd825b1075e3a326f. Exception: {}
org.openqa.selenium.JavascriptException: javascript error: a.hasAttribute is not a function

### How to reproduce the issue

```shell
It's a salesforce application and the element is inside a <lightning-input class="mb20 slds-form-element" data-aura-rendered-by="463:0" lwc-66unc5l95ad-host=""><lightning- primitive-input-simple lwc-66unc5l95ad="" aria-errormessage="help-message-114" lwc-enmikoh2qu-host="" variant="standard"><div lwc-enmikoh2qu="" part="input-text "><label lwc-enmikoh2qu="" class="slds-form-element__label slds-no-flex" for="input-115" part="label" data-form-label="" id="input-text -label-115">Document Number</label><div lwc-enmikoh2qu="" class="slds-form-element__control slds-grow" part="input-container" type="text"><input lwc- enmikoh2qu="" class="slds-input" aria-errormessage="help-message-115" id="input-115" name="tel" part="input" pattern="^([0-9]{ 2}[\.]?[0-9]{3}[\.]?[0-9]{3}[\/]?[0-9]{4}[-]?[0-9] {2})|([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{ 2})$" type="text"></div></div></lightning-primitive-input-simple></lightning-input>
```

### Logs appeared during using Healenium

```shell
[main] WARN healenium - [Save Elements] Error during save elements: [8AE8547E638761A3972C3330F759A22D_element_3]. Message: javascript error: a.hasAttribute is not a function
  (Session info: chrome=117.0.5938.92)
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [e800f12ad900e73fd825b1075e3a326f, executeScript {script=var items = [];var result = {items: null, url: null};var a = arguments[0];while (a != document) {  var child = a;  var i=0; while(child=child.previousElementSibling) i++;  var node = {tag:null,id:null,index:null,classes:[],other:{},innerText:""};  if (a.tagName !== undefined) {    node.tag = a.tagName.toLowerCase();  }  node.id = a.id;  node.index = i;  node.innerText = a.innerText;  if (a.hasAttribute("class")) {	  node.classes = a.attributes.class.value.split(' ');  }  for (index = 0; index < a.attributes.length; ++index) {      var attrName = a.attributes[index].name;      if (["id","class"].indexOf(attrName) == -1){		    node.other[attrName] = a.attributes[index].value;      }  };  items.unshift(node);  a = a.parentNode;}result.items = items;result.url = window.location.href;return JSON.stringify(result);, args=[{ELEMENT=8AE8547E638761A3972C3330F759A22D_element_3, element-6066-11e4-a52e-4f735466cecf=8AE8547E638761A3972C3330F759A22D_element_3}]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 117.0.5938.92, chrome: {chromedriverVersion: 116.0.5845.96 (1a3918166880..., userDataDir: C:\Users\A0096122\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50580}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:50580/devtoo..., se:cdpVersion: 117.0.5938.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: e800f12ad900e73fd825b1075e3a326f. Exception: {}
org.openqa.selenium.JavascriptException: javascript error: a.hasAttribute is not a function
```

### Healenium Web version

3.4.2

### Healenium Backend version

3.2.5

### Platform

Java

**Comment by Alex-Reif** [comment]
Hi @TestAutomationRecruitmentQAEngineer , 
Unfortunately, Healenium doesn't support salesforce application yet.

**Comment by Alex-Reif** [comment]
Hi @TestAutomationRecruitmentQAEngineer , 
Unfortunately, Healenium doesn't support salesforce application yet.
