### ISSUE TITLE
[BUG]: Healenium Bug - Locator Healing Issue

### ISSUE THREAD

**Issue by gem-raghavsuneja** [healenium/healenium#39]
### Describe the bug

There is a critical bug in Healenium, It is not able to heal the correct locators, i can share you the details, Kindly reach out to me for more details. This is really very critical.
raghav.suneja686@gmail.com

### How to reproduce the issue

```shell
There is a critical bug in Healenium, It is not able to heal the correct locators, i can share you the details, Kindly reach out to me for more details. This is really very critical.
raghav.suneja686@gmail.com
```

### Logs appeared during using Healenium

```shell
There is a critical bug in Healenium, It is not able to heal the correct locators, i can share you the details, Kindly reach out to me for more details. This is really very critical.
raghav.suneja686@gmail.com
```

### Healenium Web version

0.0.0

### Healenium Backend version

0.0

### Platform

Java

**Comment by Alex-Reif** [comment]
Close as duplicate https://github.com/healenium/healenium/issues/38
