### ISSUE TITLE
[BUG]: Screen shot is not working with driver = SelfHealingDriver.create(delegate);

### ISSUE THREAD

**Issue by dineshmcac** [healenium/healenium#4]
### Describe the bug

Take screen shot using driver = SelfHealingDriver.create(delegate); is throwing exception

### How to reproduce the issue

```shell
1.Go to healenium example which had driver with self healing mechanism (driver = SelfHealingDriver.create(delegate);)
2. Add srcFile = ((TakesScreenshot) webDriver).getScreenshotAs(OutputType.FILE);
3. execute the code 

Expected: screen shot must be captured
Actual Error
[ERROR] testButtonClickWithFindByAnnotationPage  Time elapsed: 38.078 s  <<< ERROR!
java.lang.ClassCastException: class com.sun.proxy.$Proxy16 cannot be cast to class org.openqa.selenium.TakesScreenshot (com.sun.proxy.$Proxy16 and org.openqa.selenium.TakesScreenshot are in unnamed module of loader 'app')
	at com.epam.healenium.tests.GeneralTest.testButtonClickWithFindByAnnotationPage(GeneralTest.java:23)
```

### Logs appeared during using Healenium

```shell
[ERROR] testButtonClickWithFindByAnnotationPage  Time elapsed: 38.078 s  <<< ERROR!
java.lang.ClassCastException: class com.sun.proxy.$Proxy16 cannot be cast to class org.openqa.selenium.TakesScreenshot (com.sun.proxy.$Proxy16 and org.openqa.selenium.TakesScreenshot are in unnamed module of loader 'app')
	at com.epam.healenium.tests.GeneralTest.testButtonClickWithFindByAnnotationPage(GeneralTest.java:23)
```

### Expected behavior

It should allow us to take screen shot

### Actual behavior

Throws  java.lang.ClassCastException: class com.sun.proxy.$Proxy16 cannot be cast to class org.openqa.selenium.TakesScreenshot 

### Healenium Web version

<healenium.version>3.2.1</healenium.version>

### Healenium Backend version

3.2.4

### Selenium version

4.1.1

### Platform

Java

**Comment by dineshmcac** [comment]
Hi @ElenaStepuro  In my project they are using shared driver - I am not able to cast
![image](https://user-images.githubusercontent.com/19305970/162966046-b3d592a1-6c94-4208-9a8d-f97780666ccf.png)

Log
java.lang.ClassCastException: class com.company.automation.web.driver.SharedDriver cannot be cast to class com.epam.healenium.SelfHealingDriver (com.gartner.automation.web.driver.SharedDriver and com.epam.healenium.SelfHealingDriver are in unnamed module of loader 'app')

**Comment by Aliaksei-Ashukha** [comment]
Hi @dineshmcac , 
In case take screenshots , we need to get delegate driver (WebDriver) and after that cast to TakesScreenshot

((TakesScreenshot) webDriver.**getDelegate**()).getScreenshotAs(OutputType.FILE);

**Comment by changan1111** [comment]
public static String takecaptureScreen(WebDriver driver) throws IOException {
		TakesScreenshot screen = ((TakesScreenshot) driver);
		File src = screen.getScreenshotAs(OutputType.FILE);
		String dest = ExtentReportUtils.reportPath + "\\" +  System.currentTimeMillis() + ".png";
		File target = new File(dest);
		FileUtils.copyFile(src, target);
		return target.getAbsolutePath();
	}

I am passing that selfhealing driver to this method from POM classes, but getting java.lang.ClassCastException: class jdk.proxy2.$Proxy17 cannot be cast to class org.openqa.selenium.TakesScreenshot (jdk.proxy2.$Proxy17 is in module jdk.proxy2 of loader 'app'; org.openqa.selenium.TakesScreenshot is in unnamed module of loader 'app')

Do I need to pass delegate driver as well to this method, or any way to cast this in that particular method..? if passing delegate to this method, the calling method also should have and the test case should have.. keep on going.. can u pls give your thoughts?

**Comment by changan1111** [comment]
Thanks @Alex-Reif . it is working..  Thanks a lot.

**Comment by changan1111** [comment]
The below is the report sample for my project.. I am expecting The Automated Testcase name to be displayed in the report which is more readable.. waitUntilPageLoadedAndElementVisible is generic method which is used to Fluentwait to see the page and locator is available to proceed.. But that is displayed in the report.. Anyway we can display the test case name which is more relevant?

com.app.pages.CommonFunctions.waitUntilPageLoadedAndElementVisible()
Failed Locator: By.linkText(Customers)
Healed Locator: By.cssSelector(div.ng-animating.ng-trigger-visible.ng-trigger.ng-tns-c124-4 > a.mat-tooltip-trigger.ng-star-inserted.ruf-menu-item.ruf-menubar-item:nth-child(1))
Score: 0.943
	

 com.app.pages.CommonFunctions.waitUntilPageLoadedAndElementVisible()
Failed Locator: By.xpath(//*[contains(text(),'Customers')])
Healed Locator: By.cssSelector(ruf-page-header-title)
Score: 0.914

**Comment by VipulK03** [comment]
i am getting error 
"java.lang.IllegalArgumentException: java.lang.ClassCastException: class jdk.proxy2.$Proxy27 cannot be cast to class org.openqa.selenium.remote.RemoteWebDriver (jdk.proxy2.$Proxy27 is in module jdk.proxy2 of loader 'app'; org.openqa.selenium.remote.RemoteWebDriver is in unnamed module of loader 'app')"
not getting where should I put getDelegate() method
