### ISSUE TITLE
[Need support]: In Latest Healenium Backend and Proxy not able to run Selenium 3 or APPIUM 1.3 versioned framework code

### ISSUE THREAD

**Issue by Naveenhd51** [healenium/healenium#64]
### Describe the problem

In Latest Healenium Backend and Proxy not able to run/Supporting Selenium 3 or APPIUM 1.3 versioned framework code

### Healenium Web version

130

### Healenium Backend version

3.4.6

### Selenium version

3 and Appium 1.3

### Platform

Java TestNG

### Logs appeared during using Healenium

```shell
500 internal server for selenium 3 and appium 1.3 version ( http:localhost:4444/wd/hub)
```

**Comment by Alex-Reif** [comment]
Only Healenium-Proxy approach available for Selenium 3
